# Generated by Django 4.0.2 on 2022-05-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.TextField(max_length=256),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
